// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/26/2026, 1:57:25 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/SE Special Project 2/PPQ/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/SE Special Project 2/PPQ/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/SE Special Project 2/PPQ/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/SE Special Project 2/PPQ/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/SE Special Project 2/PPQ/frontend/plugins/**/*.{js,ts,mjs}","C:/SE Special Project 2/PPQ/frontend/composables/**/*.{js,ts,mjs}","C:/SE Special Project 2/PPQ/frontend/utils/**/*.{js,ts,mjs}","C:/SE Special Project 2/PPQ/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/SE Special Project 2/PPQ/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/SE Special Project 2/PPQ/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/SE Special Project 2/PPQ/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;