import json
import httpx
from typing import List, Dict, Any
from app.core.config import settings

# Shared HTTP client for connection pooling to avoid DNS & SSL handshake latency
_client = httpx.AsyncClient(timeout=30.0)

async def query_gemini_assistant(
    system_instruction: str,
    contents: List[Dict[str, Any]]
) -> Dict[str, Any]:
    """
    Sends a request to the Gemini API using dynamic model configuration.
    Returns the parsed JSON response containing the assistant's reply and matching IDs.
    """
    api_key = settings.gemini_api_key
    if not api_key:
        return {
            "reply": "Lỗi cấu hình hệ thống: Gemini API Key chưa được cấu hình. Vui lòng liên hệ quản trị viên.",
            "movies": [],
            "branches": [],
            "showtimes": []
        }

    url = f"https://generativelanguage.googleapis.com/v1beta/models/{settings.gemini_model}:generateContent?key={api_key}"

    # Build response schema for structured JSON output
    response_schema = {
        "type": "OBJECT",
        "properties": {
            "reply": {
                "type": "STRING",
                "description": "Friendly Vietnamese response to the user's inquiry, summarizing options and answering questions."
            },
            "movies": {
                "type": "ARRAY",
                "items": {
                    "type": "STRING"
                },
                "description": "List of movie UUIDs that match the user's movie preference or search query."
            },
            "branches": {
                "type": "ARRAY",
                "items": {
                    "type": "STRING"
                },
                "description": "List of branch UUIDs that match the user's location/cinema preference."
            },
            "showtimes": {
                "type": "ARRAY",
                "items": {
                    "type": "STRING"
                },
                "description": "List of showtime UUIDs that strictly match the user's requested movie, location/branch, and preferred time window."
            }
        },
        "required": ["reply", "movies", "branches", "showtimes"]
    }

    payload = {
        "systemInstruction": {
            "parts": [
                {
                    "text": system_instruction
                }
            ]
        },
        "contents": contents,
        "generationConfig": {
            "responseMimeType": "application/json",
            "responseSchema": response_schema
        }
    }

    try:
        res = await _client.post(url, json=payload, headers={"Content-Type": "application/json"})
        if res.status_code != 200:
            raise RuntimeError(f"Gemini API error (HTTP {res.status_code}): {res.text}")
            
        response_json = res.json()
        candidates = response_json.get("candidates", [])
        if not candidates:
            raise ValueError("No response generated by Gemini model.")
            
        content_parts = candidates[0].get("content", {}).get("parts", [])
        if not content_parts:
            raise ValueError("Empty content generated by Gemini model.")
            
        text_response = content_parts[0].get("text", "{}")
        parsed_result = json.loads(text_response)
        
        return {
            "reply": parsed_result.get("reply", "Tôi có thể giúp gì cho bạn?"),
            "movies": parsed_result.get("movies", []),
            "branches": parsed_result.get("branches", []),
            "showtimes": parsed_result.get("showtimes", [])
        }
    except Exception as e:
        print(f"Error querying Gemini: {e}")
        return {
            "reply": "Xin lỗi, đã xảy ra lỗi trong quá trình xử lý yêu cầu bằng AI. Vui lòng thử lại sau.",
            "movies": [],
            "branches": [],
            "showtimes": []
        }

async def query_gemini_mood_matcher(
    system_instruction: str,
    prompt: str
) -> Dict[str, Any]:
    """
    Sends a prompt to Gemini and receives structured movie recommendations with reason.
    """
    api_key = settings.gemini_api_key
    if not api_key:
        return {"recommendations": []}

    url = f"https://generativelanguage.googleapis.com/v1beta/models/{settings.gemini_model}:generateContent?key={api_key}"

    # Build response schema for structured JSON output
    response_schema = {
        "type": "OBJECT",
        "properties": {
            "recommendations": {
                "type": "ARRAY",
                "items": {
                    "type": "OBJECT",
                    "properties": {
                        "movie_id": {
                            "type": "STRING",
                            "description": "UUID of the movie being recommended."
                        },
                        "reason": {
                            "type": "STRING",
                            "description": "Personalized explanation in Vietnamese of why this movie fits the user's mood/situation."
                        }
                    },
                    "required": ["movie_id", "reason"]
                },
                "description": "Top 3 movie recommendations matching the user's prompt."
            }
        },
        "required": ["recommendations"]
    }

    payload = {
        "systemInstruction": {
            "parts": [{"text": system_instruction}]
        },
        "contents": [
            {
                "role": "user",
                "parts": [{"text": prompt}]
            }
        ],
        "generationConfig": {
            "responseMimeType": "application/json",
            "responseSchema": response_schema
        }
    }

    try:
        res = await _client.post(url, json=payload, headers={"Content-Type": "application/json"})
        if res.status_code != 200:
            raise RuntimeError(f"Gemini API error (HTTP {res.status_code}): {res.text}")
            
        response_json = res.json()
        candidates = response_json.get("candidates", [])
        if not candidates:
            return {"recommendations": []}
            
        content_parts = candidates[0].get("content", {}).get("parts", [])
        if not content_parts:
            return {"recommendations": []}
            
        text_response = content_parts[0].get("text", "{}")
        parsed_result = json.loads(text_response)
        return parsed_result
    except Exception as e:
        print(f"Error querying Gemini mood matcher: {e}")
        return {"recommendations": []}
