import json
import urllib.request
import urllib.error
import asyncio
from typing import List, Dict, Any, Optional
from app.core.config import settings

async def query_gemini_assistant(
    system_instruction: str,
    contents: List[Dict[str, Any]]
) -> Dict[str, Any]:
    """
    Sends a request to the Gemini API using gemini-3.5-flash.
    Returns the parsed JSON response containing the assistant's reply and matching IDs.
    """
    api_key = settings.gemini_api_key
    if not api_key:
        return {
            "reply": "Lỗi cấu hình hệ thống: Gemini API Key chưa được cấu hình. Vui lòng liên hệ quản trị viên.",
            "movies": [],
            "branches": [],
            "showtimes": []
        }

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key={api_key}"

    # Build response schema for structured JSON output
    response_schema = {
        "type": "OBJECT",
        "properties": {
            "reply": {
                "type": "STRING",
                "description": "Friendly Vietnamese response to the user's inquiry, summarizing options and answering questions."
            },
            "movies": {
                "type": "ARRAY",
                "items": {
                    "type": "STRING"
                },
                "description": "List of movie UUIDs that match the user's movie preference or search query."
            },
            "branches": {
                "type": "ARRAY",
                "items": {
                    "type": "STRING"
                },
                "description": "List of branch UUIDs that match the user's location/cinema preference."
            },
            "showtimes": {
                "type": "ARRAY",
                "items": {
                    "type": "STRING"
                },
                "description": "List of showtime UUIDs that strictly match the user's requested movie, location/branch, and preferred time window."
            }
        },
        "required": ["reply", "movies", "branches", "showtimes"]
    }

    payload = {
        "systemInstruction": {
            "parts": [
                {
                    "text": system_instruction
                }
            ]
        },
        "contents": contents,
        "generationConfig": {
            "responseMimeType": "application/json",
            "responseSchema": response_schema
        }
    }

    # Perform synchronous HTTP request in a separate thread to keep it async friendly
    def _make_request():
        data_bytes = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            url,
            data=data_bytes,
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        try:
            with urllib.request.urlopen(req, timeout=30) as response:
                return response.read().decode("utf-8")
        except urllib.error.HTTPError as e:
            error_msg = e.read().decode("utf-8")
            raise RuntimeError(f"Gemini API error (HTTP {e.code}): {error_msg}")
        except Exception as e:
            raise RuntimeError(f"Failed to communicate with Gemini API: {str(e)}")

    try:
        response_text = await asyncio.to_thread(_make_request)
        response_json = json.loads(response_text)
        
        # Extract text from response candidate
        candidates = response_json.get("candidates", [])
        if not candidates:
            raise ValueError("No response generated by Gemini model.")
            
        content_parts = candidates[0].get("content", {}).get("parts", [])
        if not content_parts:
            raise ValueError("Empty content generated by Gemini model.")
            
        text_response = content_parts[0].get("text", "{}")
        
        # Parse the structured JSON output
        parsed_result = json.loads(text_response)
        
        # Ensure default fields are present
        return {
            "reply": parsed_result.get("reply", "Tôi có thể giúp gì cho bạn?"),
            "movies": parsed_result.get("movies", []),
            "branches": parsed_result.get("branches", []),
            "showtimes": parsed_result.get("showtimes", [])
        }
    except Exception as e:
        print(f"Error querying Gemini: {e}")
        return {
            "reply": "Xin lỗi, đã xảy ra lỗi trong quá trình xử lý yêu cầu bằng AI. Vui lòng thử lại sau.",
            "movies": [],
            "branches": [],
            "showtimes": []
        }

async def query_gemini_mood_matcher(
    system_instruction: str,
    prompt: str
) -> Dict[str, Any]:
    """
    Sends a prompt to Gemini and receives structured movie recommendations with reason.
    """
    api_key = settings.gemini_api_key
    if not api_key:
        return {"recommendations": []}

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key={api_key}"

    # Build response schema for structured JSON output
    response_schema = {
        "type": "OBJECT",
        "properties": {
            "recommendations": {
                "type": "ARRAY",
                "items": {
                    "type": "OBJECT",
                    "properties": {
                        "movie_id": {
                            "type": "STRING",
                            "description": "UUID of the movie being recommended."
                        },
                        "reason": {
                            "type": "STRING",
                            "description": "Personalized explanation in Vietnamese of why this movie fits the user's mood/situation."
                        }
                    },
                    "required": ["movie_id", "reason"]
                },
                "description": "Top 3 movie recommendations matching the user's prompt."
            }
        },
        "required": ["recommendations"]
    }

    payload = {
        "systemInstruction": {
            "parts": [{"text": system_instruction}]
        },
        "contents": [
            {
                "role": "user",
                "parts": [{"text": prompt}]
            }
        ],
        "generationConfig": {
            "responseMimeType": "application/json",
            "responseSchema": response_schema
        }
    }

    def _make_request():
        data_bytes = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            url,
            data=data_bytes,
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        try:
            with urllib.request.urlopen(req, timeout=30) as response:
                return response.read().decode("utf-8")
        except urllib.error.HTTPError as e:
            error_msg = e.read().decode("utf-8")
            raise RuntimeError(f"Gemini API error (HTTP {e.code}): {error_msg}")
        except Exception as e:
            raise RuntimeError(f"Failed to communicate with Gemini API: {str(e)}")

    try:
        response_text = await asyncio.to_thread(_make_request)
        response_json = json.loads(response_text)
        
        candidates = response_json.get("candidates", [])
        if not candidates:
            return {"recommendations": []}
            
        content_parts = candidates[0].get("content", {}).get("parts", [])
        if not content_parts:
            return {"recommendations": []}
            
        text_response = content_parts[0].get("text", "{}")
        parsed_result = json.loads(text_response)
        return parsed_result
    except Exception as e:
        print(f"Error querying Gemini mood matcher: {e}")
        return {"recommendations": []}
