<script setup lang="ts">
import { storeToRefs } from 'pinia'
import { useUserStore } from '~/store/user'
import { comboService, type CinemaCombo } from '~/services/api'

const { currentUser } = storeToRefs(useUserStore())
const rows = ref<CinemaCombo[]>([])
const loading = ref(false), saving = ref(false), modalOpen = ref(false), touched = ref(false), stockManaged = ref(true)
const error = ref(''), search = ref(''), filter = ref<'ALL'|'ACTIVE'|'LOW'|'OUT'|'HIDDEN'>('ALL')
const editing = ref<CinemaCombo|null>(null)
const brokenImages = ref(new Set<string>())
const selectedFile = ref<File|null>(null)
const localPreview = ref('')
const fileInput = ref<HTMLInputElement|null>(null)
const form = reactive({ name:'', description:'', price:59000, image_url:'', stock_quantity:20 as number|null, is_active:true })

const stats = computed(() => ({ total: rows.value.length, active: rows.value.filter(r=>r.is_active&&(r.stock_quantity==null||r.stock_quantity>0)).length, low: rows.value.filter(r=>r.is_active&&r.stock_quantity!=null&&r.stock_quantity>0&&r.stock_quantity<=5).length, out: rows.value.filter(r=>r.stock_quantity===0).length }))
const visibleRows = computed(() => rows.value.filter(r => {
  const term=search.value.trim().toLocaleLowerCase('vi'), text=`${r.name} ${r.description||''}`.toLocaleLowerCase('vi')
  return (!term||text.includes(term)) && (filter.value==='ALL'||filter.value==='ACTIVE'&&r.is_active&&(r.stock_quantity==null||r.stock_quantity>0)||filter.value==='LOW'&&r.is_active&&r.stock_quantity!=null&&r.stock_quantity>0&&r.stock_quantity<=5||filter.value==='OUT'&&r.stock_quantity===0||filter.value==='HIDDEN'&&!r.is_active)
}))
const errors = computed(() => {
  const e:Record<string,string>={}
  if(form.name.trim().length<2)e.name='Tên combo cần ít nhất 2 ký tự.'
  if(rows.value.some(r=>r.id!==editing.value?.id&&r.name.trim().toLocaleLowerCase('vi')===form.name.trim().toLocaleLowerCase('vi')))e.name='Tên combo này đã tồn tại.'
  if(!Number.isFinite(Number(form.price))||Number(form.price)<1000)e.price='Giá bán phải từ 1.000đ.'
  if(stockManaged.value&&(!Number.isInteger(Number(form.stock_quantity))||Number(form.stock_quantity)<0))e.stock='Tồn kho phải là số nguyên từ 0.'
  if(form.image_url&&!/^https?:\/\//i.test(form.image_url))e.image='URL ảnh phải bắt đầu bằng http:// hoặc https://.'
  return e
})
function money(v:number|string){return `${Number(v).toLocaleString('vi-VN')}đ`}
function state(r:CinemaCombo){if(!r.is_active)return{label:'Đã ẩn',cls:'gray'};if(r.stock_quantity===0)return{label:'Hết hàng',cls:'red'};if(r.stock_quantity!=null&&r.stock_quantity<=5)return{label:'Sắp hết',cls:'amber'};return{label:'Đang bán',cls:'green'}}
async function load(){loading.value=true;error.value='';try{rows.value=await comboService.getManage()}catch(e:any){error.value=e?.message||'Không thể tải combo.'}finally{loading.value=false}}
onMounted(load)
function reset(){if(localPreview.value)URL.revokeObjectURL(localPreview.value);selectedFile.value=null;localPreview.value='';editing.value=null;touched.value=false;stockManaged.value=true;Object.assign(form,{name:'',description:'',price:59000,image_url:'',stock_quantity:20,is_active:true})}
function create(){reset();modalOpen.value=true}
function edit(r:CinemaCombo){editing.value=r;touched.value=false;stockManaged.value=r.stock_quantity!=null;Object.assign(form,{name:r.name,description:r.description||'',price:Number(r.price),image_url:r.image_url||'',stock_quantity:r.stock_quantity??20,is_active:r.is_active});modalOpen.value=true}
function close(){if(!saving.value){modalOpen.value=false;reset()}}
function chooseImage(){fileInput.value?.click()}
function onImageSelected(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;error.value='';if(!['image/jpeg','image/png','image/webp'].includes(file.type)){error.value='Chỉ hỗ trợ ảnh JPG, PNG hoặc WEBP.';input.value='';return}if(file.size>5*1024*1024){error.value='Ảnh combo không được vượt quá 5 MB.';input.value='';return}if(localPreview.value)URL.revokeObjectURL(localPreview.value);selectedFile.value=file;localPreview.value=URL.createObjectURL(file);form.image_url=''}
function removeImage(){if(localPreview.value)URL.revokeObjectURL(localPreview.value);selectedFile.value=null;localPreview.value='';form.image_url='';if(fileInput.value)fileInput.value.value=''}
async function importStarter(){loading.value=true;error.value='';try{rows.value=await comboService.importStarter()}catch(e:any){error.value=e?.message||'Không thể thêm combo mẫu.'}finally{loading.value=false}}
async function save(){touched.value=true;error.value='';if(Object.keys(errors.value).length)return;const branchId=currentUser.value?.branchId||editing.value?.branch_id;if(!branchId){error.value='Tài khoản chưa được phân công chi nhánh.';return}saving.value=true;try{if(selectedFile.value)form.image_url=await comboService.uploadImage(selectedFile.value);const payload={branch_id:branchId,...form,name:form.name.trim(),description:form.description.trim()||null,image_url:form.image_url.trim()||null,stock_quantity:stockManaged.value?Number(form.stock_quantity):null};if(editing.value)await comboService.update(editing.value.id,payload);else await comboService.create(payload);modalOpen.value=false;reset();await load()}catch(e:any){error.value=e?.message||'Không thể lưu combo.'}finally{saving.value=false}}
async function toggle(r:CinemaCombo){try{await comboService.update(r.id,{branch_id:r.branch_id,name:r.name,description:r.description,price:r.price,image_url:r.image_url,stock_quantity:r.stock_quantity,is_active:!r.is_active});await load()}catch(e:any){error.value=e?.message||'Không thể đổi trạng thái.'}}
</script>

<template><div class="space-y-5">
  <header class="flex flex-wrap items-end justify-between gap-4"><div><p class="eyebrow">Vận hành quầy hàng</p><h2 class="text-2xl font-black text-white">Combo bắp nước</h2><p class="mt-1 text-sm text-gray-400">Quản lý sản phẩm, giá và tồn kho tại {{currentUser?.branchName||'chi nhánh được phân công'}}.</p></div><div class="flex gap-2"><button class="secondary" :disabled="loading" @click="importStarter"><span class="material-symbols-outlined">auto_awesome</span>Combo mẫu</button><button class="primary" @click="create"><span class="material-symbols-outlined">add</span>Tạo combo</button></div></header>
  <p v-if="error" class="error-box">{{error}}</p>
  <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><button class="stat" :class="{selected:filter==='ALL'}" @click="filter='ALL'"><span>Tổng combo</span><b>{{stats.total}}</b></button><button class="stat" :class="{selected:filter==='ACTIVE'}" @click="filter='ACTIVE'"><span>Đang bán</span><b class="text-emerald-400">{{stats.active}}</b></button><button class="stat" :class="{selected:filter==='LOW'}" @click="filter='LOW'"><span>Sắp hết (≤ 5)</span><b class="text-amber-300">{{stats.low}}</b></button><button class="stat" :class="{selected:filter==='OUT'}" @click="filter='OUT'"><span>Hết hàng</span><b class="text-rose-400">{{stats.out}}</b></button></section>
  <section class="panel flex flex-col gap-3 p-4 md:flex-row"><label class="search flex-1"><span class="material-symbols-outlined">search</span><input v-model="search" placeholder="Tìm tên hoặc thành phần..."></label><select v-model="filter" class="field md:w-52"><option value="ALL">Tất cả trạng thái</option><option value="ACTIVE">Đang bán</option><option value="LOW">Sắp hết</option><option value="OUT">Hết hàng</option><option value="HIDDEN">Đã ẩn</option></select></section>
  <div v-if="loading" class="panel p-14 text-center text-gray-400">Đang tải dữ liệu...</div>
  <div v-else-if="visibleRows.length" class="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><article v-for="r in visibleRows" :key="r.id" class="card"><div class="relative flex h-40 items-center justify-center overflow-hidden bg-gradient-to-br from-orange-950 to-[#151717]"><img v-if="r.image_url&&!brokenImages.has(r.id)" :src="r.image_url" :alt="r.name" class="h-full w-full object-cover" @error="brokenImages=new Set([...brokenImages,r.id])"><span v-else class="material-symbols-outlined text-7xl text-orange-300/25">fastfood</span><span class="badge" :class="state(r).cls">{{state(r).label}}</span></div><div class="p-5"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><h3 class="truncate text-lg font-black text-white">{{r.name}}</h3><p class="mt-1 line-clamp-2 min-h-10 text-sm text-gray-400">{{r.description||'Chưa cập nhật thành phần.'}}</p></div><strong class="shrink-0 text-orange-300">{{money(r.price)}}</strong></div><div class="stock"><span>Tồn kho</span><b>{{r.stock_quantity??'Không quản lý'}}<template v-if="r.stock_quantity!=null"> phần</template></b></div><div class="mt-4 flex gap-2"><button class="mini flex-1" @click="edit(r)"><span class="material-symbols-outlined">edit</span>Chỉnh sửa</button><button class="mini" :class="r.is_active?'text-amber-300':'text-emerald-300'" @click="toggle(r)">{{r.is_active?'Ngừng bán':'Mở bán'}}</button></div></div></article></div>
  <div v-else class="panel p-14 text-center text-gray-400">Không tìm thấy combo phù hợp.<button class="ml-2 font-bold text-red-400" @click="search='';filter='ALL'">Xóa lọc</button></div>
  <Teleport to="body"><div v-if="modalOpen" class="overlay" @click.self="close"><form class="modal" @submit.prevent="save"><div class="flex justify-between"><div><p class="eyebrow">{{editing?'Cập nhật sản phẩm':'Sản phẩm mới'}}</p><h3 class="text-xl font-black text-white">{{editing?editing.name:'Tạo combo bắp nước'}}</h3></div><button type="button" class="text-gray-400" @click="close"><span class="material-symbols-outlined">close</span></button></div><div class="mt-5 grid gap-4 md:grid-cols-2">
    <label class="md:col-span-2"><span class="label">Tên combo *</span><input v-model="form.name" class="field" :class="{invalid:touched&&errors.name}" placeholder="Combo Couple"><small v-if="touched&&errors.name" class="err">{{errors.name}}</small></label><label><span class="label">Giá bán *</span><input v-model.number="form.price" type="number" min="1000" step="1000" class="field" :class="{invalid:touched&&errors.price}"><small v-if="touched&&errors.price" class="err">{{errors.price}}</small></label><label class="md:col-span-2"><span class="label">Hình ảnh combo</span><input ref="fileInput" type="file" accept="image/jpeg,image/png,image/webp" class="hidden" @change="onImageSelected"><div class="image-picker"><img v-if="localPreview||form.image_url" :src="localPreview||form.image_url" class="h-28 w-36 rounded-xl object-cover"><span v-else class="material-symbols-outlined text-5xl text-orange-300/30">add_photo_alternate</span><div class="flex-1"><b class="block text-sm text-white">{{selectedFile?.name||'Chọn ảnh từ máy tính'}}</b><small class="mt-1 block text-gray-500">JPG, PNG hoặc WEBP · tối đa 5 MB</small><div class="mt-3 flex flex-wrap gap-2"><button type="button" class="mini" @click="chooseImage"><span class="material-symbols-outlined">upload</span>{{localPreview||form.image_url?'Đổi ảnh':'Chọn ảnh'}}</button><button v-if="localPreview||form.image_url" type="button" class="mini text-rose-300" @click="removeImage">Xóa ảnh</button></div></div></div><details class="mt-2"><summary class="cursor-pointer text-xs text-gray-500">Hoặc sử dụng URL hình ảnh</summary><input v-model="form.image_url" class="field mt-2" :class="{invalid:touched&&errors.image}" placeholder="https://..."><small v-if="touched&&errors.image" class="err">{{errors.image}}</small></details></label><label class="md:col-span-2"><span class="label">Thành phần</span><textarea v-model="form.description" rows="3" class="field resize-none" placeholder="01 bắp lớn + 02 nước vừa"></textarea></label>
    <div class="box md:col-span-2"><label class="flex items-center justify-between"><span><b class="block text-sm text-white">Quản lý tồn kho</b><small class="text-gray-500">Tắt nếu không cần theo dõi số lượng.</small></span><input v-model="stockManaged" type="checkbox" class="check"></label><label v-if="stockManaged" class="mt-4 block"><span class="label">Số phần hiện có</span><input v-model.number="form.stock_quantity" type="number" min="0" class="field" :class="{invalid:touched&&errors.stock}"><small v-if="touched&&errors.stock" class="err">{{errors.stock}}</small><small v-else-if="form.stock_quantity===0" class="mt-1 block text-amber-300">Combo hết hàng sẽ không xuất hiện khi khách đặt vé.</small></label></div><label class="box md:col-span-2 flex items-center justify-between"><span><b class="block text-sm text-white">Mở bán cho khách</b><small class="text-gray-500">Tắt để ẩn nhưng vẫn giữ lịch sử.</small></span><input v-model="form.is_active" type="checkbox" class="check"></label>
  </div><div class="mt-6 flex justify-end gap-2"><button type="button" class="mini px-5" @click="close">Hủy</button><button class="primary px-6" :disabled="saving">{{saving?'Đang lưu...':editing?'Lưu thay đổi':'Tạo combo'}}</button></div></form></div></Teleport>
</div></template>

<style scoped>
.panel,.card,.modal{border:1px solid rgba(255,255,255,.08);border-radius:1rem;background:#1a1c1c}.card{overflow:hidden;transition:.2s}.card:hover{transform:translateY(-2px);border-color:#f9731640}.eyebrow{font-size:.72rem;font-weight:900;text-transform:uppercase;letter-spacing:.16em;color:#f87171}.primary,.secondary,.mini{display:inline-flex;align-items:center;justify-content:center;gap:.35rem;border-radius:.75rem;font-weight:800}.primary{background:#e50914;padding:.7rem 1rem;color:white}.secondary{border:1px solid #fb923c50;background:#fb923c12;padding:.7rem 1rem;color:#fed7aa}.mini{border:1px solid #ffffff1a;padding:.55rem .75rem;font-size:.8rem;color:#bae6fd}.stat{border:1px solid #ffffff14;border-radius:1rem;background:#1a1c1c;padding:1rem 1.25rem;text-align:left}.stat span{display:block;font-size:.7rem;font-weight:800;text-transform:uppercase;color:#9ca3af}.stat b{display:block;margin-top:.2rem;font-size:1.7rem}.stat.selected{border-color:#ef444488;background:#7f1d1d22}.field,.search{width:100%;border:1px solid #ffffff1a;border-radius:.75rem;background:#101212;color:white;outline:none}.field{padding:.75rem}.search{display:flex;align-items:center;gap:.5rem;padding:0 .75rem}.search input{width:100%;background:transparent;padding:.75rem 0;outline:none}.field:focus,.search:focus-within{border-color:#ef4444aa;box-shadow:0 0 0 3px #ef44441a}.stock,.box{margin-top:1rem;border-radius:.75rem;background:#0003;padding:.7rem .8rem}.stock{display:flex;justify-content:space-between;font-size:.85rem}.stock span{color:#9ca3af}.badge{position:absolute;left:.75rem;top:.75rem;border-radius:999px;padding:.3rem .7rem;font-size:.7rem;font-weight:900}.green{background:#10b98120;color:#6ee7b7}.amber{background:#f59e0b20;color:#fcd34d}.red{background:#f43f5e20;color:#fda4af}.gray{background:#6b728020;color:#9ca3af}.overlay{position:fixed;inset:0;z-index:110;display:flex;align-items:center;justify-content:center;background:#000c;padding:1rem}.modal{max-height:92vh;width:100%;max-width:680px;overflow-y:auto;padding:1.5rem}.label{margin-bottom:.35rem;display:block;font-size:.7rem;font-weight:800;text-transform:uppercase;color:#9ca3af}.err{margin-top:.3rem;display:block;font-size:.72rem;font-weight:700;color:#fda4af}.invalid{border-color:#fb7185!important}.check{height:1.2rem;width:1.2rem;accent-color:#e50914}.error-box{border:1px solid #f43f5e4d;border-radius:.75rem;background:#f43f5e1a;padding:.75rem 1rem;font-size:.85rem;font-weight:700;color:#fda4af}
.image-picker{display:flex;min-height:9rem;align-items:center;gap:1rem;border:1px dashed #ffffff24;border-radius:.85rem;background:#101212;padding:1rem}
</style>
